### ISSUE TITLE
Filue input attribute.

### ISSUE THREAD

**Issue by ghost** [eXsio/vaadin-plupload#4]
Do you support File input attribute(http://stackoverflow.com/a/10503561/1246520)? 
I just found PluploadFilter which is some kind of server side filter, or am I wrong?

**Comment by eXsio** [comment]
An instance of PluploadFilter is a server side object, which is being serialized and sent to client-side Plupload library in order to configure it (via the `setOption` function). See more here: http://www.plupload.com/docs/Options#filters
