### ISSUE TITLE
Vaadin4Spring + plupload

### ISSUE THREAD

**Issue by gandos** [eXsio/vaadin-plupload#5]
Hi, 
i have a problem after i use this addon in my application that powered by vaadin4spring (https://github.com/peholmst/vaadin4spring). 

everytime i tried to run my application, it always give me an error "Requested resource [/VAADIN/widgetsets/pl.exsio.plupload.PluploadWidgetSet/pl.exsio.plupload.PluploadWidgetSet.nocache.js] not found from filesystem or through class loader". 

it seem somehow, class dev.DevUI.DevServlet in addon jar override my application main servlet for /\* path

thank u for a great addon :)

**Comment by eXsio** [comment]
Hi.

Thanks for noticing that, the DevUI shouldn't be in the production build. Turned out it was a type-o in my POM file. Fixed it in 8b8a09c76838cedbb707b829161ecaace18a3f72. There's a new version (1.5.4) waiting for You in the Vaadin Directory. I'm glad that You like the addon :)

cheers :)

**Comment by gandos** [comment]
great, now its perfect. thanks :)
